automatisch/automatisch

- README.md
> docs(readme): remove github community link

- packages/backend/src/graphql/queries/get-apps.ts
- packages/backend/src/graphql/schema.graphql
- packages/web/src/components/ChooseAppAndEventSubstep/index.tsx
- packages/web/src/components/ExecutionStep/index.tsx
- packages/web/src/components/FlowStep/index.tsx
- packages/web/src/graphql/queries/get-apps.ts
> fix: only show apps with actions in action step

- packages/backend/src/apps/twilio/index.ts
- packages/backend/src/apps/twilio/triggers/index.ts
- packages/backend/src/apps/twilio/triggers/receive-sms/fetch-messages.ts
- packages/backend/src/apps/twilio/triggers/receive-sms/index.ts
Checked out from https://github.com/automatisch/automatisch/pull/651
> feat: Implement twilio new sms trigger

- packages/backend/src/graphql/schema.graphql
- packages/web/src/graphql/queries/get-app-connections.ts
- packages/web/src/graphql/queries/get-app.ts
Fixes: https://github.com/automatisch/automatisch/issues/654
> chore: Remove available apps enum type and use string instead

- packages/backend/src/apps/slack/actions/send-a-message-to-channel/index.ts
- packages/backend/src/apps/slack/actions/send-a-message-to-channel/post-message.ts
- packages/backend/src/apps/slack/auth/create-auth-data.ts
- packages/backend/src/apps/slack/auth/index.ts
- packages/backend/src/apps/slack/auth/is-still-verified.ts
- packages/backend/src/apps/slack/auth/verify-credentials.ts
- packages/backend/src/apps/slack/common/add-auth-header.ts
- packages/backend/src/apps/slack/common/get-current-user.ts
- packages/backend/src/helpers/compute-parameters.ts
- packages/docs/pages/apps/slack/connection.md
- packages/types/index.d.ts
> feat(slack): add bot capability in send message action

- packages/web/src/components/ExecutionStep/index.tsx
> feat(web): hide empty error tab in execution step

- packages/types/index.d.ts
- packages/web/src/components/ExecutionRow/index.tsx
- packages/web/src/graphql/queries/get-executions.ts
- packages/web/src/locales/en.json
> feat(web): add status in execution row

- packages/e2e-tests/cypress.config.js
- packages/e2e-tests/cypress/e2e/apps/list-apps.js
- packages/e2e-tests/cypress/e2e/connections/create-connection.js
- packages/e2e-tests/cypress/e2e/executions/display-execution.js
- packages/e2e-tests/cypress/e2e/flow-editor/create-flow.js
targets to #698, as I covered its test in this branch.
> test: replace Slack with DeepL

- packages/web/src/components/FlowStep/index.tsx
> feat: add circular progress in flow step

- docker-compose.yml
- docker/Dockerfile
- docker/entrypoint.sh
Addresses #735.
Let me know if you prefer different values for the healthcheck interval, timeout, retries. I used the default from the example at https://github.com/peter-evans/docker-compose-healthcheck/blob/master/docker-compose.yml
> refactor: use healthcheck for db, remove psql client from image

- docker/Dockerfile
An alpine image based reduces the image size by almost half without further optimizations.
> chore: switch to alpine based image

- packages/backend/src/graphql/schema.graphql
- packages/web/src/components/ChooseAppAndEventSubstep/index.tsx
- packages/web/src/graphql/queries/get-app.ts
- packages/web/src/graphql/queries/get-apps.ts
- packages/web/src/locales/en.json
> feat: show "instant" chip for webhook triggers

- packages/web/src/components/AddNewAppConnection/index.tsx
> feat: take search bar out of scroll in add app connection

- packages/backend/src/config/app.ts
> feat: prioritize WEB_APP_URL

- packages/docs/pages/advanced/configuration.md
Fixes https://github.com/automatisch/automatisch/issues/803
> docs: Add WEB_APP_URL and WEBHOOK_URL to configuration

- packages/web/src/graphql/mutations/update-step.ts
> fix(Editor): fetch webhookUrl upon updating step

- packages/backend/src/server.ts
Provide a full URL with HTTP protocol on server launch up in development mode.
Resolves #846
> chore(backend): Provide HTTP url on server launch up

- packages/backend/src/apps/todoist/auth/index.ts
Added missing OAuth redirect URL field on creating Todoist application connection.
> fix(todoist): Add missing OAuth redirect URL field

- README.md
Current command needs public key so access is denied.
> fix: readme git clone command

- packages/backend/src/apps/slack/auth/generate-auth-url.ts
- packages/backend/src/apps/slack/dynamic-data/list-channels/index.ts
- Listing im channels in Slack
- Showing all the available channels
p.s. Existing connections must reconnect as a new scope is introduced!
> feat(slack/list-channels): add im channels and increase limit

- packages/backend/src/apps/http-request/actions/custom-request/index.ts
- packages/backend/src/graphql/schema.graphql
- packages/backend/src/helpers/app-info-converter.ts
- packages/backend/src/helpers/http-client/index.ts
- packages/types/index.d.ts
- packages/web/src/components/DynamicField/index.tsx
- packages/web/src/components/FlowStep/index.tsx
- packages/web/src/components/FlowSubstep/FilterConditions/index.tsx
- packages/web/src/components/InputCreator/index.tsx
- packages/web/src/components/PowerInput/index.tsx
- packages/web/src/components/PowerInput/style.ts
- packages/web/src/graphql/queries/get-apps.ts
> feat(http-request): add headers support

- packages/backend/src/apps/google-drive/dynamic-data/list-folders/index.ts
- packages/backend/src/apps/google-drive/triggers/new-files-in-folder/index.ts
- packages/backend/src/apps/google-drive/triggers/new-files-in-folder/new-files-in-folder.ts
- packages/backend/src/apps/google-drive/triggers/new-files/new-files.ts
- packages/backend/src/apps/google-drive/triggers/new-folders/index.ts
- packages/backend/src/apps/google-drive/triggers/new-folders/new-folders.ts
- packages/backend/src/apps/google-drive/triggers/updated-files/index.ts
- packages/backend/src/apps/google-drive/triggers/updated-files/updated-files.ts
- packages/backend/src/apps/google-sheets/dynamic-data/list-spreadsheets/index.ts
- packages/backend/src/apps/google-sheets/triggers/new-spreadsheets/new-spreadsheets.ts
> fix(shared-drive): show shared drive items

- packages/backend/src/apps/google-drive/dynamic-data/list-folders/index.ts
- packages/backend/src/apps/google-drive/triggers/new-files-in-folder/new-files-in-folder.ts
- packages/backend/src/apps/google-drive/triggers/new-files/new-files.ts
- packages/backend/src/apps/google-drive/triggers/new-folders/new-folders.ts
- packages/backend/src/apps/google-drive/triggers/updated-files/updated-files.ts
- packages/backend/src/apps/google-sheets/dynamic-data/list-spreadsheets/index.ts
- packages/backend/src/apps/google-sheets/triggers/new-spreadsheets/new-spreadsheets.ts
> fix(shared-drive): add missing field to payload

- packages/backend/src/apps/rss/triggers/new-items-in-feed/new-items-in-feed.ts
> feat(rss/new-items-in-feed): incorporate attributes

- packages/backend/src/helpers/compute-parameters.ts
Fixes https://github.com/automatisch/automatisch/issues/1175
> fix: allow colon while computing step parameters

- packages/web/src/graphql/queries/get-apps.ts
> fix(get-apps): fetch additionalFields for triggers

- packages/backend/src/graphql/mutations/execute-flow.ts
- packages/backend/src/graphql/mutations/update-flow-status.ts
- packages/backend/src/graphql/mutations/update-step.ts
- packages/backend/src/helpers/compute-parameters.ts
> feat: enhance step variable coverage

- packages/types/index.d.ts
- packages/web/src/components/SsoProviders/index.ee.tsx
- packages/web/src/graphql/mutations/upsert-saml-auth-providers-role-mappings.ts
- packages/web/src/graphql/queries/get-saml-auth-provider-role-mappings.ts
- packages/web/src/graphql/queries/get-saml-auth-provider.ts
- packages/web/src/hooks/useSamlAuthProvider.ts
- packages/web/src/hooks/useSamlAuthProviderRoleMappings.ts
- packages/web/src/locales/en.json
- packages/web/src/pages/Authentication/RoleMappings.tsx
- packages/web/src/pages/Authentication/RoleMappingsFieldsArray.tsx
- packages/web/src/pages/Authentication/SamlConfiguration.tsx
- packages/web/src/pages/Authentication/index.tsx
[AUT-241](https://linear.app/automatisch/issue/AUT-241/create-role-mapping-section-on-the-same-page)
> feat: introduce role mappings form on authentication page

- packages/web/src/components/ChooseAppAndEventSubstep/index.tsx
- packages/web/src/components/ExecutionStep/index.tsx
- packages/web/src/components/FlowStep/index.tsx
- packages/web/src/hooks/useApps.ts
As requested in this task [AUT-258](https://linear.app/automatisch/issue/AUT-258/create-a-page-for-admin-settingsapps) I created a separate PR for this refactor. When it is merged I will update the use-case in AUT-258.
> refactor: introduce useApps hook

- packages/backend/src/apps/notion/actions/create-page/index.ts
> feat(notion/create-page): support variables in parentPageId field

- packages/backend/src/apps/removebg/actions/index.ts
- packages/backend/src/apps/removebg/actions/remove-image-background/index.ts
- packages/backend/src/apps/removebg/index.ts
- packages/docs/pages/.vitepress/config.js
- packages/docs/pages/apps/removebg/actions.md
- packages/docs/pages/guide/available-apps.md
> feat(removebg): add `remove image background` action

- .github/workflows/playwright.yml
Note this is a test PR for now so I can make sure the correct test runs are made
> test: run UI workflow only on changes outside of backend apps

- packages/web/src/components/Layout/index.tsx
- packages/web/src/components/NotFound/index.tsx
- packages/web/src/locales/en.json
- packages/web/src/routes.tsx
[AUT-656](https://linear.app/automatisch/issue/AUT-656/create-404-page)
> feat: introduce 404 page

- packages/web/src/routes.tsx
[AUT-655](https://linear.app/automatisch/issue/AUT-655/do-not-let-users-access-notifications-page-when-its-turned-off)
> feat: do not let users access notifications page when it's turned off

- packages/web/src/components/EditorLayout/index.jsx
- packages/web/src/components/EditorLayout/style.js
- packages/web/src/styles/theme.js
[AUT-782](https://linear.app/automatisch/issue/AUT-782/flow-editor-topbar-should-be-sticky)
> feat: make flow editor topbar sticky

- packages/web/src/components/ChooseAppAndEventSubstep/index.jsx
- packages/web/src/components/ChooseConnectionSubstep/index.jsx
- packages/web/src/components/ControlledCustomAutocomplete/index.jsx
- packages/web/src/components/InputCreator/index.jsx
- packages/web/src/components/PowerInput/index.jsx
[AUT-493](https://linear.app/automatisch/issue/AUT-493/indicate-whenever-a-field-is-required-within-editor)
> feat: introduce asterisk for all the required fields

- packages/e2e-tests/README.md
Added the README for setting up e2e-tests.
> Write basic README for setting up the tests

- packages/web/src/hooks/useApps.js
- packages/web/src/pages/AdminApplications/index.jsx
I noticed a bug with useApps on /admin-settings/apps.
> fix: introduce fix for useApps not using name as param

- packages/web/src/components/UsageDataInformation/index.ee.jsx
- packages/web/src/hooks/usePlanAndUsage.js
[AUT-919](https://linear.app/automatisch/issue/AUT-919/call-for-plan-and-usage-data-incorrect)
> fix: pass current user id to usePlanAndUsage hook

- packages/web/src/pages/Application/index.jsx
[AUT-922](https://linear.app/automatisch/issue/AUT-922/disable-create-flow-button-for-un-authorized-users)
> fix: disable create flow button when user doesn't have permissions

- packages/web/src/components/ControlledCustomAutocomplete/index.jsx
- packages/web/src/components/InputCreator/index.jsx
- packages/web/src/components/PowerInput/style.js
[AUT-920](https://linear.app/automatisch/issue/AUT-920/not-all-inputs-look-disabled-when-flow-published)
> fix: make inputs look and behave disabled when flow is in published state

- packages/web/src/hooks/useDynamicData.js
**Reproduction steps:**
1. Create a flow using the github > new issues event
2. Select any repositories that have labels (should be available by default)
3. No labels would be found
**Actual result:**
No labels would be found even though there should be labels.
**Expected result:**
The labels configured in the repository should be displayed as options in the "label" dropdown.
> fix(useDynamicData): send correct payload to API

- packages/backend/src/apps/formatter/actions/date-time/transformers/format-date-time.js
> feat(formatter/format-date-time): add unix to datetime support

- render.yaml
> fix(render.yaml): correct docker contexts

- packages/web/src/components/EditorNew/Edge/Edge.jsx
- packages/web/src/components/EditorNew/EditorNew.jsx
- packages/web/src/components/EditorNew/FlowStepNode/FlowStepNode.jsx
- packages/web/src/components/EditorNew/constants.js
- packages/web/src/components/EditorNew/useAutoLayout.js
- packages/web/src/components/EditorNew/useScrollBoundaries.js
- packages/web/src/components/EditorNew/utils.js
- packages/web/src/components/FlowStep/index.jsx
I fixed the bug happening when nodes are added. There was a problem with concurrent nodes state updates, when active step state also changed. I introduce improvements to nodes and edges management.
> feat: improve nodes and edges state update

- packages/web/src/components/DynamicField/index.jsx
Problem with rendering in DynamicField component with long variables #1933
This fix makes DynamicField look in next way:
> Fix issue #1933

- packages/web/src/components/FlowSubstep/index.jsx
This reverts commit 017a8814944575afd37fa0616377cb248a3d75e2.
> Revert "feat: persist parameters values in FlowSubstep (#1505)"

- packages/web/src/components/EditorLayout/index.jsx
[AUT-1074](https://linear.app/automatisch/issue/AUT-1074/error-when-trying-to-save-empty-flow-with-only-create-role)
I also removed optimisticResponse since indeed it is obsolete now.
> fix: fix error for only Create role when publishing flow

- packages/web/src/components/AddAppConnection/index.jsx
- packages/web/src/components/ChooseConnectionSubstep/index.jsx
[AUT-1088](https://linear.app/automatisch/issue/AUT-1088/uncaught-exception-on-close-dialog-with-add-connection)
> fix: introduce fix for undefined id on dialog close when adding a connection

- packages/web/src/components/AppBar/style.js
- packages/web/src/components/CustomLogo/style.ee.js
- packages/web/src/pages/Login/index.jsx
[AUT-1091](https://linear.app/automatisch/issue/AUT-1091/stretched-logo-on-login-page)
> fix: introduce fix for logo being stretched

- packages/web/src/components/FlowSubstep/FilterConditions/index.jsx
[AUT-1064](https://linear.app/automatisch/issue/AUT-1064/input-fields-out-of-bounds-for-filter-action)
> fix: introduce fix for overflowing inputs with long parameters names

- packages/web/public/index.html
- packages/web/public/manifest.json
> feat: remove PWA

- packages/backend/src/graphql/mutations/update-step.js
resolves [AUT-1098](https://linear.app/automatisch/issue/AUT-1098/i-was-able-to-publish-invalid-flow)
> fix: mark steps incomplete when their parameters change

- packages/backend/src/graphql/mutations/update-flow-status.js
- packages/backend/src/models/flow.js
resolves [AUT-1094](https://linear.app/automatisch/issue/AUT-1094/technical-error-in-snackbar-message)
> fix(update-flow-status): throw at incomplete trigger step

- packages/backend/src/apps/carbone/actions/add-template/index.js
resolves [AUT-1090](https://linear.app/automatisch/issue/AUT-1090/typo-in-carbone-action)
> fix(carbone/add-template): correct typo in template

- packages/backend/src/graphql/mutations/duplicate-flow.js
resolves [AUT-1093](https://linear.app/automatisch/issue/AUT-1093/cant-duplicate-flow-of-another-user)
> fix(duplicate-flow): let users duplicate flows they have access to

- packages/backend/src/apps/clickup/actions/create-folder/index.js
- packages/backend/src/apps/clickup/actions/create-list/index.js
- packages/backend/src/apps/clickup/actions/index.js
- packages/backend/src/apps/clickup/assets/favicon.svg
- packages/backend/src/apps/clickup/auth/generate-auth-url.js
- packages/backend/src/apps/clickup/auth/index.js
- packages/backend/src/apps/clickup/auth/is-still-verified.js
- packages/backend/src/apps/clickup/auth/verify-credentials.js
- packages/backend/src/apps/clickup/common/add-auth-header.js
- packages/backend/src/apps/clickup/common/get-current-user.js
- packages/backend/src/apps/clickup/dynamic-data/index.js
- packages/backend/src/apps/clickup/dynamic-data/list-folders/index.js
- packages/backend/src/apps/clickup/dynamic-data/list-lists/index.js
- packages/backend/src/apps/clickup/dynamic-data/list-spaces/index.js
- packages/backend/src/apps/clickup/dynamic-data/list-tasks/index.js
- packages/backend/src/apps/clickup/dynamic-data/list-workspaces/index.js
- packages/backend/src/apps/clickup/index.js
- packages/backend/src/apps/clickup/triggers/index.js
- packages/backend/src/apps/clickup/triggers/new-folders/index.js
- packages/backend/src/apps/clickup/triggers/new-lists/index.js
- packages/backend/src/apps/clickup/triggers/new-tasks/index.js
- packages/backend/src/apps/clickup/triggers/task-changes/index.js
- packages/backend/src/apps/clickup/triggers/updated-task/index.js
- packages/docs/pages/.vitepress/config.js
- packages/docs/pages/apps/clickup/actions.md
- packages/docs/pages/apps/clickup/connection.md
- packages/docs/pages/apps/clickup/triggers.md
- packages/docs/pages/guide/available-apps.md
- packages/docs/pages/public/favicons/clickup.svg
> feat(clickup): add clickup integration

- packages/e2e-tests/fixtures/flow-editor-page.js
- packages/e2e-tests/tests/app-integrations/webhook.spec.js
- packages/e2e-tests/tests/flow-editor/create-flow.spec.js
- packages/web/src/components/EditableTypography/index.jsx
- packages/web/src/components/EditorLayout/index.jsx
- packages/web/src/components/TestSubstep/index.jsx
I have provided a set of webhook test.
Sometimes when I run those I see error with "reduce"
> test: add simple webhook flow test

- packages/web/src/components/FlowStep/index.jsx
[AUT-1183](https://linear.app/automatisch/issue/AUT-1183/step-becomes-incomplete-even-though-i-changed-nothing)
> feat: update step only when data changes

- packages/web/src/components/TestSubstep/index.jsx
[AUT-1132](https://linear.app/automatisch/issue/AUT-1132/multiple-testandcontinue-possible)
> fix: prevent resetting test data until data is loaded

- packages/backend/src/apps/clickup/index.js
- packages/backend/src/apps/jotform/index.js
- packages/backend/src/apps/mailchimp/index.js
- packages/backend/src/apps/mailerlite/index.js
Although part of URL is changed to variable, there are no docs for updated apps.
> fix: use env var for authDocUrl

- packages/web/src/components/SignUpForm/index.ee.jsx
[AUT-1253](https://linear.app/automatisch/issue/AUT-1253/no-error-on-signup-with-existing-user-email)
> feat: add error snackbar for errors originating from registerUser function

- packages/web/src/pages/Authentication/RoleMappings.jsx
- packages/web/src/pages/Authentication/RoleMappingsFieldsArray.jsx
[AUT-1239](https://linear.app/automatisch/issue/AUT-1239/no-snackbar-on-error-save-role-mappings)
> feat: add error snackbar for updating role mappings

- packages/web/src/hooks/useAdminCreateSamlAuthProvider.js
- packages/web/src/hooks/useAdminUpdateSamlAuthProvider.js
- packages/web/src/pages/Authentication/SamlConfiguration.jsx
[AUT-1231](https://linear.app/automatisch/issue/AUT-1231/no-snackbar-on-error-authentication-config)
> feat: add error snackbar when creating or updating saml auth provider

- packages/web/src/components/ControlledAutocomplete/index.jsx
- packages/web/src/components/Form/index.jsx
- packages/web/src/components/TextField/index.jsx
- packages/web/src/pages/Authentication/RoleMappings.jsx
- packages/web/src/pages/Authentication/RoleMappingsFieldsArray.jsx
[AUT-1325](https://linear.app/automatisch/issue/AUT-1325/introduce-uniqueness-validation-for-the-remote-role-name-in-the-saml)
> feat: introduce uniqueness validation for remote role name

- packages/web/src/components/PermissionCatalogField/PermissionCatalogFieldLoader/index.jsx
- packages/web/src/components/PermissionCatalogField/index.ee.jsx
- packages/web/src/pages/CreateRole/index.ee.jsx
- packages/web/src/pages/EditRole/index.ee.jsx
[AUT-1384](https://linear.app/automatisch/issue/AUT-1384/improve-createrole-form)
> feat: disable inputs when data is loading

- packages/docs/pages/advanced/configuration.md
Fixes https://github.com/automatisch/automatisch/issues/2254
> docs: Add REDIS_DB env variable to configuration

- packages/backend/src/workers/trigger.js
resolves [AUT-1414](https://linear.app/automatisch/issue/AUT-1414/error-undefined-was-passed-to-findbyid)
> fix(workers): correct worker for trigger queue

- packages/backend/src/controllers/api/v1/apps/get-flows.js
- packages/backend/src/controllers/api/v1/connections/get-flows.js
Should resolve [AUT-1217](https://linear.app/automatisch/issue/AUT-1217/double-flow-visible)
> fix(apps/get-flows): respond with distinct flows

- packages/web/src/components/AdminSettingsLayout/Footer/index.jsx
- packages/web/src/components/AdminSettingsLayout/index.jsx
- packages/web/src/locales/en.json
[AUT-1313](https://linear.app/automatisch/issue/AUT-1313/display-deployed-version-in-frontend-somewhere)
> feat: add footer component with version display to AdminSettingsLayout

- packages/web/src/components/ChooseAppAndEventSubstep/index.jsx
- packages/web/src/hooks/useStepConnection.js
[AUT-1422](https://linear.app/automatisch/issue/AUT-1422/step-data-are-not-cleared-after-app-is-changed-to-another)
> feat: clear connection on app change in flow step

- packages/web/src/components/ImportFlowDialog/index.jsx
- packages/web/src/helpers/errors.js
[AUT-1436](https://linear.app/automatisch/issue/AUT-1436/white-screen-after-upload-wrong-filow-json-file-when-uploading-flow)
> fix: add check if errors exist in getUnifiedErrorMessage function

- packages/backend/src/apps/gmail/actions/index.js
- packages/backend/src/apps/gmail/actions/send-to-trash/index.js
- packages/backend/src/apps/gmail/actions/star-email/index.js
- packages/backend/src/apps/gmail/auth/refresh-token.js
- packages/backend/src/apps/gmail/common/add-auth-header.js
- packages/backend/src/apps/gmail/dynamic-data/index.js
- packages/backend/src/apps/gmail/dynamic-data/list-messages/index.js
- packages/docs/pages/apps/gmail/actions.md
> feat(gmail): add star email action

- packages/backend/src/apps/gmail/actions/index.js
- packages/backend/src/apps/gmail/actions/send-to-trash/index.js
- packages/backend/src/apps/gmail/actions/star-email/index.js
- packages/backend/src/apps/gmail/auth/refresh-token.js
- packages/backend/src/apps/gmail/common/add-auth-header.js
- packages/backend/src/apps/gmail/dynamic-data/index.js
- packages/backend/src/apps/gmail/dynamic-data/list-messages/index.js
- packages/docs/pages/apps/gmail/actions.md
> feat(gmail): add send to trash action

- packages/backend/src/apps/gmail/actions/create-draft/index.js
- packages/backend/src/apps/gmail/actions/index.js
- packages/backend/src/apps/gmail/actions/send-to-trash/index.js
- packages/backend/src/apps/gmail/actions/star-email/index.js
- packages/backend/src/apps/gmail/auth/refresh-token.js
- packages/backend/src/apps/gmail/common/add-auth-header.js
- packages/backend/src/apps/gmail/dynamic-data/index.js
- packages/backend/src/apps/gmail/dynamic-data/list-messages/index.js
- packages/docs/pages/apps/gmail/actions.md
> feat(gmail): add create draft action

- packages/backend/src/apps/gmail/actions/create-draft/index.js
- packages/backend/src/apps/gmail/actions/index.js
- packages/backend/src/apps/gmail/actions/reply-to-email/index.js
- packages/backend/src/apps/gmail/actions/send-to-trash/index.js
- packages/backend/src/apps/gmail/actions/star-email/index.js
- packages/backend/src/apps/gmail/auth/refresh-token.js
- packages/backend/src/apps/gmail/common/add-auth-header.js
- packages/backend/src/apps/gmail/dynamic-data/index.js
- packages/backend/src/apps/gmail/dynamic-data/list-messages/index.js
- packages/backend/src/apps/gmail/dynamic-data/list-threads/index.js
- packages/docs/pages/apps/gmail/actions.md
> feat(gmail): add reply to email action

- packages/backend/src/apps/gmail/actions/create-draft/index.js
- packages/backend/src/apps/gmail/actions/index.js
- packages/backend/src/apps/gmail/actions/reply-to-email/index.js
- packages/backend/src/apps/gmail/actions/send-email/index.js
- packages/backend/src/apps/gmail/actions/send-to-trash/index.js
- packages/backend/src/apps/gmail/actions/star-email/index.js
- packages/backend/src/apps/gmail/auth/refresh-token.js
- packages/backend/src/apps/gmail/common/add-auth-header.js
- packages/backend/src/apps/gmail/dynamic-data/index.js
- packages/backend/src/apps/gmail/dynamic-data/list-emails/index.js
- packages/backend/src/apps/gmail/dynamic-data/list-messages/index.js
- packages/backend/src/apps/gmail/dynamic-data/list-signatures/index.js
- packages/backend/src/apps/gmail/dynamic-data/list-threads/index.js
- packages/backend/src/apps/gmail/index.js
- packages/docs/pages/.vitepress/config.js
- packages/docs/pages/apps/gmail/actions.md
> feat(gmail): add send email action

- packages/backend/src/apps/gmail/actions/create-draft/index.js
- packages/backend/src/apps/gmail/actions/index.js
- packages/backend/src/apps/gmail/actions/reply-to-email/index.js
- packages/backend/src/apps/gmail/actions/send-email/index.js
- packages/backend/src/apps/gmail/actions/send-to-trash/index.js
- packages/backend/src/apps/gmail/actions/star-email/index.js
- packages/backend/src/apps/gmail/auth/refresh-token.js
- packages/backend/src/apps/gmail/auth/verify-credentials.js
- packages/backend/src/apps/gmail/common/add-auth-header.js
- packages/backend/src/apps/gmail/dynamic-data/index.js
- packages/backend/src/apps/gmail/dynamic-data/list-emails/index.js
- packages/backend/src/apps/gmail/dynamic-data/list-labels/index.js
- packages/backend/src/apps/gmail/dynamic-data/list-messages/index.js
- packages/backend/src/apps/gmail/dynamic-data/list-signatures/index.js
- packages/backend/src/apps/gmail/dynamic-data/list-threads/index.js
- packages/backend/src/apps/gmail/index.js
- packages/backend/src/apps/gmail/triggers/index.js
- packages/backend/src/apps/gmail/triggers/new-emails/index.js
- packages/docs/pages/.vitepress/config.js
- packages/docs/pages/apps/gmail/actions.md
- packages/docs/pages/apps/gmail/triggers.md
- packages/docs/pages/guide/available-apps.md
> feat(gmail): add new emails trigger

- packages/web/src/components/EditorLayout/FlowFolder.jsx
> refactor: remove not used elements in FlowFolder

- packages/web/src/components/CreateFolderDialog/index.jsx
- packages/web/src/components/EditFolderDialog/index.jsx
[AUT-1467](https://linear.app/automatisch/issue/AUT-1467/create-folder-react-warning)
[AUT-1468](https://linear.app/automatisch/issue/AUT-1468/update-folder-react-warning)
> fix: CreateFolderDialog and EditFolderDialog errors

- packages/web/src/components/Folders/index.jsx
- packages/web/src/locales/en.json
[AUT-1457](https://linear.app/automatisch/issue/AUT-1457/add-feedback-when-folder-is-removed)
> feat: add feedback when folder is removed

- packages/web/src/components/SearchInput/index.jsx
- packages/web/src/pages/Flows/index.jsx
[AUT-1494](https://linear.app/automatisch/issue/AUT-1494/fix-search-bar-to-work-in-harmony-with-folders)
> feat: fix search bar to work in harmony with folders

- packages/web/src/components/PowerInput/data.js
[AUT-1502](https://linear.app/automatisch/issue/AUT-1502/some-boolean-values-are-not-displayed)
> feat: show stringified sampleValue in PowerInput

- packages/web/src/locales/en.json
- packages/web/src/pages/EditRole/index.ee.jsx
[AUT-1304](https://linear.app/automatisch/issue/AUT-1304/no-snackbar-when-update-role-failed)
I aligned error handling to how it is done in CreateRole form.
> feat: show errors in EditRole form

- packages/web/src/components/AdminTemplateContextMenu/index.jsx
- packages/web/src/components/FlowsButtons/index.jsx
- packages/web/src/components/TemplatesDialog/TemplateItem/TemplateItem.ee.jsx
- packages/web/src/components/TemplatesDialog/index.ee.jsx
- packages/web/src/hooks/useAdminDeleteTemplate.ee.js
- packages/web/src/pages/AdminCreateTemplate/index.jsx
- packages/web/src/pages/AdminUpdateTemplate/index.jsx
- packages/web/src/pages/Editor/create.jsx
- packages/web/src/pages/Flows/index.jsx
[AUT-1501](https://linear.app/automatisch/issue/AUT-1501/delete-already-deleted-template-from-create-flow-fails)
[AUT-1499](https://linear.app/automatisch/issue/AUT-1499/white-screen-on-update-already-deleted-template)
[AUT-1500](https://linear.app/automatisch/issue/AUT-1500/create-flow-from-already-deleted-template-doesnt-proceed-to-anything)
> feat: handle 404 template error

- packages/e2e-tests/fixtures/admin/users-page.js
https://github.com/automatisch/automatisch/actions/runs/14195985402/job/39771117610
> test: reorder assertions for user page related tests

- packages/web/src/components/FlowFolderChangeDialog/index.jsx
- packages/web/src/locales/en.json
[AUT-1492](https://linear.app/automatisch/issue/AUT-1492/enhance-flow-move-to-function-with-better-feedback)
> feat: disable moving flow to a folder

- packages/backend/src/apps/notion/actions/index.js
- packages/backend/src/apps/notion/actions/update-database-item/index.js
- packages/backend/src/apps/notion/dynamic-data/index.js
- packages/backend/src/apps/notion/dynamic-data/list-database-items/index.js
- packages/backend/src/apps/notion/dynamic-data/list-databases/index.js
- packages/backend/src/apps/notion/dynamic-data/list-tags/index.js
- packages/backend/src/apps/notion/dynamic-fields/index.js
- packages/backend/src/apps/notion/dynamic-fields/list-database-properties/index.js
- packages/backend/src/apps/notion/index.js
- packages/docs/pages/apps/notion/actions.md
> feat(notion): add update database item action

- packages/backend/src/apps/hubspot/actions/create-contact/index.js
- packages/backend/src/apps/hubspot/actions/index.js
- packages/backend/src/apps/hubspot/actions/update-contact/index.js
- packages/docs/pages/apps/hubspot/actions.md
> feat(hubspot): add update contact action

- packages/backend/src/apps/changedetection/dynamic-data/index.js
- packages/backend/src/apps/changedetection/dynamic-data/list-watches/index.js
- packages/backend/src/apps/changedetection/index.js
- packages/backend/src/apps/changedetection/triggers/changed-watch/index.js
- packages/backend/src/apps/changedetection/triggers/index.js
- packages/docs/pages/.vitepress/config.js
- packages/docs/pages/apps/changedetection/triggers.md
> feat(changedetection): add changed watch trigger

- packages/backend/src/apps/changedetection/actions/delete-watch/index.js
- packages/backend/src/apps/changedetection/actions/index.js
- packages/backend/src/apps/changedetection/dynamic-data/index.js
- packages/backend/src/apps/changedetection/dynamic-data/list-watches/index.js
- packages/backend/src/apps/changedetection/index.js
- packages/backend/src/apps/changedetection/triggers/changed-watch/index.js
- packages/backend/src/apps/changedetection/triggers/index.js
- packages/docs/pages/.vitepress/config.js
- packages/docs/pages/apps/changedetection/actions.md
- packages/docs/pages/apps/changedetection/triggers.md
> feat(changedetection): add delete watch action

- packages/backend/src/apps/wordpress/actions/create-user/index.js
- packages/backend/src/apps/wordpress/actions/delete-post/index.js
- packages/backend/src/apps/wordpress/actions/find-post/index.js
- packages/backend/src/apps/wordpress/actions/find-user/index.js
- packages/backend/src/apps/wordpress/actions/index.js
- packages/backend/src/apps/wordpress/dynamic-data/list-posts/index.js
- packages/docs/pages/apps/wordpress/actions.md
> feat(wordpress): add find post action

- packages/backend/src/apps/ntfy/actions/send-message/index.js
> feat(ntfy/send-message): add priority and tag fields
