README.md

docs(readme): remove trailing slash in docs link

---

packages/backend/src/helpers/compute-parameters.ts

As the variables with an underscore are not computed, I have extended the variable RegExp to cover underscores.

fix: cover _ in variable regex

---

packages/web/src/graphql/queries/get-apps.ts

The information about adding a connection in the add new connection dialog on the editor page is added.
**before**
**after**

feat: show doc info in auth dialog in editor

---

docker/images/main/wait-for-postgres.sh
docker/images/worker/wait-for-postgres.sh

resolves #723
@ksurl, we think this may be the cause, as you mentioned. Could you please give this a try if it helps you out?

fix: use actual DB name in wait for postgres script

---

docker-compose.yml

local build was using automatisch-main and automatisch-worker as the build tags despite setting the tags.
switched to setting the image name which is used by docker compose build.

fix: update compose image tag

---

packages/web/src/components/ControlledAutocomplete/index.tsx
packages/web/src/components/Editor/index.tsx
packages/web/src/components/FlowSubstep/index.tsx
packages/web/src/components/InputCreator/index.tsx

This should help us with filtering in Autocomplete components where we have multiple options with the same label even though they have different values.

fix(ControlledAutocomplete): use option value as option key

---

packages/docs/pages/.vitepress/config.js
packages/docs/pages/apps/todoist/triggers.md
packages/docs/pages/guide/available-apps.md

I have overlooked some cases in the documentation review of #826. Therefore, I have created this pull request to;
- Add it to the available apps page
- Move the "create task" trigger from the actions page to the triggers page
- Add it into the navigation configuration as we manually configure the nav

docs(todoist): restructure trigger and add in nav

---

packages/backend/src/helpers/error-handler.ts

Not solving it but related to https://github.com/automatisch/automatisch/issues/1009
Instead of exposing just the error message for the error handler, we will also expose the error stack.
cc: @pareeohnos

fix: Expose error stack together with error message

---

packages/backend/src/graphql/mutations/generate-auth-url.ts

resolves scenarios like where we receive 403, but it's actually a Cloudflare security check which the user can pass through on the browser.

fix: stop checking auth urls

---

packages/backend/src/apps/discord/dynamic-data/list-channels/index.ts

Announcement channels have a separate [channel type](https://discord.com/developers/docs/resources/channel#channel-object-channel-types) from text channels even though they're essentially the same. This fix makes them show in the channel selection as they should.

fix(discord): show announcement channels in selection

---

packages/backend/src/apps/postgresql/actions/delete/index.ts
packages/backend/src/apps/postgresql/actions/insert/index.ts
packages/backend/src/apps/postgresql/actions/sql-query/index.ts
packages/backend/src/apps/postgresql/actions/update/index.ts
packages/backend/src/apps/postgresql/auth/verify-credentials.ts

Previously db connections were never closed causing a "too many clients already" error to eventually occur, making the database unusable.
This just closes each connection once they're done so that doesn't happen.

fix(postgresql): close connections when done

---

packages/e2e-tests/tests/flow-editor/create-flow.spec.js

Updated the test into many `test.step`'s, this way we have guaranteed serial running of the steps within the main flow test, but still have partitioned sections which are easy to read/understand.

test: refactor create flow test cases with test.step

---

packages/backend/src/graphql/mutations/create-user.ee.ts

In an unlicensed installation, the user creation fails as the logic tries to use a non-existing `user` role. The changes here aim to use the default admin role we know exists.

fix: use default role for fallback user creation

---

packages/web/src/adminSettingsRoutes.tsx
packages/web/src/components/AdminSettingsLayout/index.tsx
packages/web/src/components/AppRow/index.tsx
packages/web/src/config/urls.ts
packages/web/src/graphql/queries/get-apps.ts
packages/web/src/locales/en.json
packages/web/src/pages/AdminApplications/index.tsx
packages/web/src/pages/Applications/index.tsx

[AUT-257](https://linear.app/automatisch/issue/AUT-257/create-a-sidebar-link-on-admin-settings)  [AUT-258](https://linear.app/automatisch/issue/AUT-258/create-a-page-for-admin-settingsapps)
Currently connections count and flow count returned from getApps are empty. It should be like this for now, right?
I didn't know if I should set any restrictions for accessing /admin-settings/apps page, so if there should be any let me know.

feat: introduce admin apps page

---

packages/backend/src/config/app.js

We need the ability to override apiUrl in config. SVG images are not loading when hosted with GAE with a domain eg. 
HOST: www.xyz.com
PROTOCOL: https
PORT: 8080
With the above environment, the apiUrl and baseUrl would be https://www.xyz.com:8080. There is currently no way to remove the port from the baseUrl. This pull request allows you to set the API_URL as an environment variable. If not set, the previous behavior is maintained.

feat(config): add ability to override apiUrl in environment variables

---

packages/web/src/hooks/useTrialStatus.ee.js

[AUT-619](https://linear.app/automatisch/issue/AUT-619/page-crashes-after-refreshing-and-letting-the-backend-server-stop)
[Link to the video](https://www.loom.com/share/820d10e60e4a440d82dd961b3e586165?sid=3d91ddb5-9326-434a-aae9-1cb25d8993ec) - there are errors after closing the backend but web app doesn't crash.

fix: add optional chaining to data.getTrialStatus check

---

packages/e2e-tests/fixtures/admin/roles-page.js
packages/e2e-tests/tests/admin/manage-roles.spec.js
packages/web/src/adminSettingsRoutes.jsx
packages/web/src/components/AccountDropdownMenu/index.jsx
packages/web/src/components/AdminSettingsLayout/index.jsx
packages/web/src/routes.jsx

[AUT-563](https://linear.app/automatisch/issue/AUT-563/menu-opens-whe-accessing-admin-settingsauthentication-page)
[Link to the video](https://www.loom.com/share/2831218f4dd342c08f906a52cc074974?sid=d8ce0443-7daf-4955-ad43-e52eb274ec84) - menu state is preserved (open/closed). Previously the state would refresh when clicked on Authentication menu item due to AdminLayout rerendering. To preserve the state it is better to render layout once as recommended in the[ react-router documentation](https://reactrouter.com/en/main/start/concepts#layout-routes).

feat: render AdminSettingsLayout once for all child routes

---

packages/web/src/components/PermissionCatalogField/PermissionSettings.ee.jsx

[AUT-606](https://linear.app/automatisch/issue/AUT-606/createedit-role-pages-are-not-scrollable-on-small-viewports)
[Link to video](https://www.loom.com/share/21e49603a7de4de1aec17c847a0e37e8?sid=b5287fa1-efa4-43fe-bef1-9e78917e94e8)

fix: remove unnecessery styling causing the problem with scrolling Edit/Create role pages

---

packages/web/src/components/PublicLayout/index.jsx

@barinali I noticed that public layout wasn't displayed correctly after making header sticky in the flow editor. I introduce a fix.

fix: introduce a fix for the content container height in the PublicLayout component

---

packages/web/src/components/QueryClientProvider/index.jsx
packages/web/src/hooks/useAutomatischConfig.js

We have endpoints serving 404 when no data is available for the instance or the user. Therefore, we're happy with no `data` from queries. However, before this branch, React Query kept retrying the failed requests on the mount, causing an infinite loop* in a brand-new installation.
I have turned off the `retryOnMount` feature and suggest we use it on purpose whenever we think it may be needed.
\* It can be reproduced on the login page in a brand-new installation. The logic will keep re-fetching the utomatisch config on the mount as there is no config available by default.

fix: disable retry on mount by default

---

packages/web/src/components/SplitButton/index.jsx
packages/web/src/pages/Application/index.jsx

[AUT-921](https://linear.app/automatisch/issue/AUT-921/disablehide-create-a-connection-button-in-step-connections-for-un)

fix: disable add connection button for unauthorized users

---

packages/web/src/components/SsoProviders/index.ee.jsx

**Reproduction steps:**
1. Make sure the non-enterprise edition is running
2. Go to /login
3. There will be an empty block right below the login form
**Actual result:**
There is an empty block right below the login form on /login
**Expected result:**
There shouldn't be an empty block right below the login form on /login

fix(SsoProviders): hide empty block

---

packages/web/src/components/EditorNew/EditorNew.jsx

I additionaly removed Stack, because I noticed it was imported but not used.

feat: hide react-flow attribution

---

packages/web/src/components/AppConnectionContextMenu/index.jsx
packages/web/src/components/AppConnections/index.jsx
packages/web/src/components/AppFlows/index.jsx
packages/web/src/pages/Application/index.jsx
packages/web/src/pages/Applications/index.jsx

[AUT-620](https://linear.app/automatisch/issue/AUT-620/inconsistent-uiux-without-connection-permissions)
[AUT-621](https://linear.app/automatisch/issue/AUT-621/creating-a-new-connection-with-an-unauthorized-user-gives-opaque-error)
After the changes it is not possible to enter the app's connections tab from /apps page if user doesn't have at least read permissions. It is still possible to enter via link `/app/$appKey/connections`, but connections are not shown. It is problematic to redirect user to other page based on persmissions, since they are updated asynchronously and redirect would need to happen based on permissions loading state. I think the simpler solution is good enough. 
I also introduced some missing permissions logic when using connection's context menu.

feat: improve UI display depending on user permissions

---

packages/web/src/components/ControlledCustomAutocomplete/index.jsx

[AUT-1038](https://linear.app/automatisch/issue/AUT-1038/persisted-value-doesnt-appear)
The value of the field that depended on other field was reset, because the hook that reset the field ran on mount on the component, even if the value of the field didn't change.
In the fix I prevent the reset to run on mount of the component, assuming that previous values should be displayed in state they were saved.

fix: persist value in ControlledCustomAutocomplete when it depends on other fields

---

packages/web/src/components/EditorLayout/index.jsx

[AUT-1070](https://linear.app/automatisch/issue/AUT-1070/console-error-when-trying-to-publish-invalid-flow)
It seems that this error can be safely ignored on the frontend.

feat: use try-catch block for updating flow status

---

packages/web/src/components/NoResultFound/index.jsx
packages/web/src/pages/Editor/create.jsx
packages/web/src/pages/Flows/index.jsx

[AUT-1076](https://linear.app/automatisch/issue/AUT-1076/infinite-circular-progress-for-only-update-role-when-trying-to-add)
In Editor/create.jsx null is returned on error to prevent infinite loading status. This page is only accessible through direct link for users without flow creation permissions, so it should be uncommon for them to try to access it. But as an improvement I think a link to /flows page could be added to show something instead of blank page with error snackbar. @barinali let me know if I should add it.

feat: block access to flow creation for users without permissions

---

packages/web/src/index.jsx

[AUT-1069](https://linear.app/automatisch/issue/AUT-1069/flowexecutions-time-is-not-english-only)
I noticed the same problem happens in other places like in AppConnectionRow, ExecutionRow or ExecutionHeader, so I set the 'en' locale globally.

fix: set default locale for luxon's  DateTime

---

packages/web/src/components/EditorNew/EditorNew.jsx
packages/web/src/components/EditorNew/useScrollBoundaries.js

[AUT-1007](https://linear.app/automatisch/issue/AUT-1007/limit-vertical-scroll-to-a-reasonable-boundary)
Since in react-flow scroll happens by `transform: translate` it is tricky to get the scroll back. Therefore I would suggest to use the old version of the flow editor for now (REACT_APP_USE_NEW_FLOW_EDITOR env variable set to false), that looks the same and has the scroll. And when the paths branching is introduce, the editor will need to have zoom and pan as in Zapier (without scroll) and the new editor could be used. Is that all right?
In this PR I only added scroll boundry for scrolling down.

feat: limit vertical scroll to a reasonable boundary

---

packages/web/src/components/FlowSubstep/FilterConditions/index.jsx

[AUT-1131](https://linear.app/automatisch/issue/AUT-1131/filter-criteria-cant-be-added-after-removal)

fix: prevent removing last filter criteria

---

packages/web/src/components/FlowStep/index.jsx

[AUT-1065](https://linear.app/automatisch/issue/AUT-1065/undefined-cannot-be-found)
When clicking Enter after typing something in "Choose an app" and not selecting one of the options, onSubmit function of the form was triggered, since this input in the moment of selecting an app is the only input wrapped in form tag. The inputs in ChooseAppAndEventSubstep and ChooseConnectionSubstep are not wrapped in Controller component from react-hook-form therefore they should not trigger handleSubmit of react-hook-form form, they have their own handlers for when the data is submitted when clicking  "Continue". That is why I removed this components from the Form wrapper. 
I didn't add additional prevention for submitting the value in dropdowns without variables, because from my investigation it is not …

fix: in FlowStep wrap in Form component only controlled inputs

---

packages/backend/src/apps/github/actions/create-issue/index.js

resolves [AUT-1089](https://linear.app/automatisch/issue/AUT-1089/github-repo-not-marked-as-required-when-create-issue-action-is-added)

fix(github/create-issue): mark repo field as required

---

packages/web/src/pages/CreateUser/index.jsx

[AUT-1141](https://linear.app/automatisch/issue/AUT-1141/role-not-marked-as-required-but-throws-an-error-when-empty)

feat: make role input required in CreateUser

---

packages/web/src/components/Form/index.jsx

[AUT-1190](https://linear.app/automatisch/issue/AUT-1190/filter-default-fields-disappear-on-active-step-change)
The issue arises from resetting the form in the custom Form component when defaultValues change. Specifically, the DynamicField and FilterConditions compontents set their default field value within a useEffect, but this value gets overwritten by the form reset triggered in the Form component. This happens because, in React, child useEffect hooks are executed before the parent's useEffect.
To preserve the default values of child components, I implemented a limit on the number of resets performed by the Form componen.

fix: limit resetting form on defaultValues change

---

packages/web/src/components/PowerInput/SuggestionItem.jsx
packages/web/src/components/Slate/Variable.jsx

[AUT-1097](https://linear.app/automatisch/issue/AUT-1097/invalid-prop-type-when-setting-up-action-ntfy)

feat: allow both number and string values as sampleValue

---

packages/web/src/components/SubscriptionCancelledAlert/index.ee.jsx

[AUT-1167](https://linear.app/automatisch/issue/AUT-1167/invalid-datetime-after-free-plan-is-done)

feat: check if cancellationEffectiveDateObject is a valid date

---

packages/web/src/components/Slate/Variable.jsx

[AUT-1152](https://linear.app/automatisch/issue/AUT-1152/no-label-in-filter-when-the-other-one-is-removed)
The problem was caused by Slate editor focusing on empty placehorder Slate element (children). All the text was pushed to the left, but it was still affected by overflow hidden, that it why it was invisible. Since the slate element is always empty for Variable, since it is a void element, I put it at the beginning, so the text doesn't shift.
The issue occurred because the Slate editor focuses on an empty placeholder element (Slate's children), causing all the text to be aligned to the left and rendered invisible due to the `overflow: hidden` property. Since the placeholder Slate element for Variable is always empty (as variable is a void element), I repositioned it at the beginning …

fix: variable chip label disappearing

---

packages/backend/src/apps/wordpress/auth/index.js

[AUT-1280](https://linear.app/automatisch/issue/AUT-1280/non-required-url-for-wordpress-connection-leads-to-500-error)

feat: make Wordpress instanceUrl field required

---

packages/web/src/components/SearchInput/index.jsx
packages/web/src/pages/Flows/index.jsx

[AUT-1347](https://linear.app/automatisch/issue/AUT-1347/pagination-not-applied-on-a-page-reload)
To implement the required behavior, I also needed to persist the search value in addition to the page number.
When a user duplicates a flow, I’ve added a redirection to the first page, as flows are ordered by creation date, with the newest flow displayed first.

feat: persist pagination and search value on flows page

---

packages/web/src/components/AcceptInvitationForm/index.jsx
packages/web/src/components/AddAppConnection/index.jsx
packages/web/src/components/AdminApplicationAuthClientDialog/index.jsx
packages/web/src/components/InstallationForm/index.jsx
packages/web/src/components/LoginForm/index.jsx
packages/web/src/components/TestSubstep/index.jsx
packages/web/src/pages/CreateUser/index.jsx
packages/web/src/pages/Execution/index.jsx
packages/web/src/pages/ProfileSettings/index.jsx
packages/web/src/styles/theme.js

[AUT-1364](https://linear.app/automatisch/issue/AUT-1364/make-error-messages-appear-inline-in-login-form)
Inline error:
I also unified font weight for the Alert and AlertTitle. I made the font weight of Alert to be 400, since it is the original Mui Alert font weight and I believe it looks the best.

feat: inline login form error and unify Alert font weight

---

packages/web/src/components/ForgotPasswordForm/index.ee.jsx
packages/web/src/components/LoginForm/index.jsx
packages/web/src/components/ResetPasswordForm/index.ee.jsx

[AUT-1365](https://linear.app/automatisch/issue/AUT-1365/inline-error-messages-in-resetpasswordform-and-forgotpasswordform)
Additionaly I also changed Alert import for LoginForm, as I noticed it is not consistent with other material-ui components imports. Also I added `erros?.message` to be displayed if there is no errors object.
In ForgotPasswordForm for success message I also used Alert and moved it before the submit button, to unify the look with error alerts.

feat: introduce inline error messages for ForgotPassword and ResetPasswordForm

---

packages/web/src/components/AddAppConnection/index.jsx
packages/web/src/components/ChooseConnectionSubstep/index.jsx
packages/web/src/locales/en.json

[AUT-1389](https://linear.app/automatisch/issue/AUT-1389/add-feedback-on-failed-adding-connection-with-predefined-auth-client)

feat: add error snackbar on failed app authentication

---

packages/web/src/components/AdminApplicationOAuthClientUpdateDialog/index.jsx
packages/web/src/components/AdminApplicationOAuthClientUpdateDialog/style.js
packages/web/src/components/AdminApplicationUpdateOAuthClient/index.jsx
packages/web/src/locales/en.json

[AUT-1388](https://linear.app/automatisch/issue/AUT-1388/empty-values-sent-when-updating-auth-clients)

feat: introduce two separate forms in update auth client dialog

---

packages/web/src/components/TestSubstep/index.jsx

[AUT-1423](https://linear.app/automatisch/issue/AUT-1423/cannot-scroll-on-steps-when-using-react-app-use-new-flow-editor=true)

feat: apply React Flow's 'nowheel' class to enable scroll in test output

---

packages/e2e-tests/tests/app-integrations/webhook.spec.js
packages/web/src/components/CodeEditor/index.jsx
packages/web/src/components/ControlledAutocomplete/index.jsx
packages/web/src/components/DynamicField/index.jsx
packages/web/src/components/InputCreator/index.jsx
packages/web/src/components/TextField/index.jsx

[AUT-1409](https://linear.app/automatisch/issue/AUT-1409/incorporate-default-values-for-fields-in-step-arguments)
I tested various configurations of substep arguments and now it seems to me that default values are consistently applied. For `DynamicField`, the default value of the field takes precedence and is used if it exists. If not, the parent node's default value is applied. Otherwise, an empty string is used. When fields have default values, these defaults are applied each time fields are added:
I recorded a video showing how the default values are applied:
https://www.loom.com/share/6b933a74b9c74fae9e3a44b3e4f3ec25
Each time I open and close the step, because default values are applied on Form mount.

feat: accept falsy default values

---

packages/web/src/components/EditableTypography/index.jsx
packages/web/src/components/FlowStep/index.jsx

Usage of EditableTypography was causing some console errors:

fix: remove not used props passed to EditableTypography and fix propTypes

---

packages/e2e-tests/tests/admin/applications.spec.js
packages/web/src/components/AdminApplicationSettings/index.jsx

[AUT-1454](https://linear.app/automatisch/issue/AUT-1454/hide-oauth-relevant-option-in-app-config-if-appsupportsoauthclients-is)

feat: hide oauth relevant option in app config if supportsOauthClients is false

---

packages/web/src/components/ChooseConnectionSubstep/index.jsx

[AUT-1424](https://linear.app/automatisch/issue/AUT-1424/freshly-added-connection-is-not-selected)

fix: correctly set initial option value in ChooseConnectionSubstep

---

packages/backend/src/apps/formatter/actions/date-time/index.js
packages/backend/src/apps/formatter/actions/numbers/index.js
packages/backend/src/apps/formatter/actions/text/index.js
packages/backend/src/apps/formatter/dynamic-fields/list-replace-regex-options/index.js
packages/backend/src/apps/formatter/dynamic-fields/list-transform-options/date-time/format-date-time.js
packages/backend/src/apps/formatter/dynamic-fields/list-transform-options/numbers/format-number.js
packages/backend/src/apps/formatter/dynamic-fields/list-transform-options/numbers/format-phone-number.js
packages/backend/src/apps/formatter/dynamic-fields/list-transform-options/numbers/perform-math-operation.js
packages/backend/src/apps/formatter/dynamic-fields/list-transform-options/text/replace.js

I didn't change it for Date/Time format options as it was working fine with custom variables to some point.

fix: do not use variables in Formatter transform options

---

packages/web/src/components/ChooseAppAndEventSubstep/index.jsx

[AUT-1479](https://linear.app/automatisch/issue/AUT-1479/transform-value-remembered-when-action-event-is-changed)

fix: clear parameters on event change in ChooseAppAndEventSubstep

---

packages/web/src/components/EditorNew/EditorNew.jsx

[AUT-1433](https://linear.app/automatisch/issue/AUT-1433/react-error-when-adding-action-steps)
I implemented a debounce on the onAddStep function to address this issue. However, the "Maximum update depth exceeded" error can still occur if a user quickly triggers updates on different nodes. I plan to create a separate task to optimize the updates for nodes and edges.

feat: debounce onAddStep in EditorNew

---

packages/web/src/components/FileUploadInput/index.js
packages/web/src/components/ImportFlowDialog/index.jsx
packages/web/src/locales/en.json

[AUT-1466](https://linear.app/automatisch/issue/AUT-1466/long-file-name-makes-select-file-button-broken#comment-a02fac07)

feat: handle long file names in ImportFlowDialog

---

packages/web/src/components/ControlledCustomAutocomplete/Options.jsx

[AUT-1419](https://linear.app/automatisch/issue/AUT-1419/react-issues-on-click-attributevalue-for-signalwire-add-xml-node)
If the secondary content needs to be displayed as a string, even when it is of a different type such as number or boolean, please let me know. I can then convert the value to a string instead of checking its type.

feat: display secondary ListItemText content only if is a string

---

packages/web/src/components/ControlledAutocomplete/index.jsx

[AUT-1416](https://linear.app/automatisch/issue/AUT-1416/failed-prop-type-invalid-prop-children-supplied-to)
If option value content needs to be displayed as a string, even when it is of a different type such as number or boolean, please let me know. I can then convert the value to a string instead of checking its type.

feat: display option value only if it is a string

---

packages/web/src/hooks/useFlowFolder.js

[AUT-1465](https://linear.app/automatisch/issue/AUT-1465/after-folder-removal-flow-seems-to-be-still-in-the-folder)

feat: handle 404 error in useFlowFolder

---

packages/docs/pages/.vitepress/theme/custom.css

The icons vary significantly, so to ensure a cohesive look, I removed the rounding and reduced their size to fit within the circle.
For dark mode, I set the background circle to white to maintain clear visibility of all icons.

fix: apps icons position

---

packages/web/src/components/ControlledAutocomplete/index.jsx
packages/web/src/components/ControlledAutocomplete/style.js

[AUT-1461](https://linear.app/automatisch/issue/AUT-1461/make-the-human-readable-names-bold-when-variable-is-false)
Since the ControlledAutocomplete component may or may not display the option value, I render the listbox items differently based on the showOptionValue setting. I aligned the styles with ControlledCustomAutocomplete.

feat: align the style of ControlledAutocomplete with ControlledCustomAutocomplete

---

packages/web/src/components/EditorLayout/index.jsx
packages/web/src/components/FlowContextMenu/index.jsx
packages/web/src/components/FlowRow/index.jsx

[AUT-1341](https://linear.app/automatisch/issue/AUT-1341/going-back-in-app-from-a-flow-from-within-a-page-other-than-1-returns)

feat: preserve query params when navigating back to flow page from flow editor

---

packages/web/src/components/JSONViewer/index.jsx

[AUT-1195](https://linear.app/automatisch/issue/AUT-1195/flow-page-unresponsive-when-request-is-executed)
@barinali @kuba618  The page becomes unresponsive when JSONViewer has to render a large amount of deeply nested data. My solution is to expand only the first level of nodes by default. I can also add an "Expand All" button, allowing users to expand everything if needed. However, please note that doing so may still cause the page to become temporarily unresponsive.
Let me know if you'd like me to add this feature. If keeping the JSON output fully expanded - despite occasional unresponsiveness - is not a major concern, I can close this pull request.

fix: expand only first level of nodes on load

---

packages/web/src/components/ChooseConnectionSubstep/index.jsx
packages/web/src/components/FlowStep/index.jsx

[AUT-1513](https://linear.app/automatisch/issue/AUT-1513/connections-list-inside-flow-is-not-stable)
@kuba618 this bug is difficult to reproduce, but I was able to replicate it a couple of times. It appears that the handleChange event wasn’t triggered correctly because its dependency array was missing stepConnection?.id, causing it to use an outdated value.
I was able to replicate the issue where the connection list displayed an incorrect number of items under a throttled network. I resolved it by preventing connection changes while data is being fetched after a selection. Changing the selected connection mid-request can lead to inconsistencies.

fix: resolve issue with incorrect connections list

---

packages/backend/src/apps/gmail/auth/generate-auth-url.js
packages/backend/src/apps/google-calendar/auth/generate-auth-url.js
packages/backend/src/apps/google-drive/auth/generate-auth-url.js
packages/backend/src/apps/google-forms/auth/generate-auth-url.js
packages/backend/src/apps/google-sheets/auth/generate-auth-url.js
packages/backend/src/apps/google-tasks/auth/generate-auth-url.js
packages/backend/src/apps/youtube/auth/generate-auth-url.js

This change should fix https://github.com/automatisch/automatisch/issues/1579 issue.
1. Authenticate for any Google product (eg. Google Sheets)
2. Go to **"My Apps"** -> **"Google Sheets"**
3. Select **"Connections"** tab
4. Delete the connection
5. Re-authenticate for the same product again with the same account.
After 60 minutes  run your automation. Your `access_token` will expire and refresh token request will return error:
```
{
"error": "invalid_grant"
"error_description": "Bad Request"
}
```
I've described why this happening in my reply to the issue here: https://github.com/automatisch/automatisch/issues/1579#issuecomment-2993675456
This will demonstrate visually how Google OAuth returns responses based on the `prompt` value.
On this image you can see, that response does not …

Fix Google Authetication missing refresh token 

---

packages/backend/src/apps/telegram-bot/actions/send-message/index.js

This PR introduces a new **parse mode option** for the Telegram bot integration, enabling more flexible message formatting when sending messages through the bot. With this enhancement, users can now easily specify the desired parse mode (such as `Markdown`, `MarkdownV2`, or `HTML`) to control how Telegram renders the message content.
Previously, messages sent via the Telegram bot did not provide an option to set the parse mode, limiting formatting capabilities. This update addresses that limitation, allowing for richer, more expressive messages and supporting a wider range of Telegram features.
- Added a `parse_mode` option in the Telegram bot action configuration.
- Updated the Telegram action logic to include the `parse_mode` parameter when sending messages via the Telegram API.
- …

feat(telegram-bot): add parse mode option for message formatting
